### ISSUE TITLE
[RangeError: Maximum call stack size exceeded] when applying 'autolog'

### ISSUE THREAD

**Issue by weilonge** [seiyugi/debuguy#62]
The following log will happen on some source codes when applying 'autolog' command:
adding log shared/js/dialer/contacts.js
parsing failed: shared/js/dialer/contacts.js
[RangeError: Maximum call stack size exceeded]

**Comment by weilonge** [comment]
This issue can be reproduced by applying 'autolog' at a source code with try/catch block inside.

**Comment by begeeben** [comment]
Fixed.
