### ISSUE TITLE
npm install fails at postinstall script 'gulp hook'

### ISSUE THREAD

**Issue by begeeben** [seiyugi/debuguy#71]
20224 error node v0.12.1
20225 error npm  v2.5.1
20226 error code ELIFECYCLE
20227 error debuguy@0.0.2 postinstall: `gulp hook`
20227 error Exit status 1
20228 error Failed at the debuguy@0.0.2 postinstall script 'gulp hook'.
20228 error This is most likely a problem with the debuguy package,
20228 error not with npm itself.
20228 error Tell the author that this fails on your system:
20228 error     gulp hook
20228 error You can get their info via:
20228 error     npm owner ls debuguy
20228 error There is likely additional logging output above.

**Comment by dwi2** [comment]
This is duplicate of #88
